"""Static presentation of saved research artifacts. No downloads, fits or solves."""
from html import escape as e
import json, shutil, os
from pathlib import Path
from src.research.provenance import write_json,object_id,digest
PAGES=['overview','risk','decision','performance','scenarios','models','research']
LABELS={'overview':'Overview','risk':'Risk','decision':'Decision','performance':'Performance','scenarios':'Scenarios','models':'Models','research':'Research'}
COLORS=['#73d4da','#ffcb85','#9cafef','#db9dc0','#87c693','#c4bca7']

def number(v,decimals=1): return 'N/A' if v is None else f'{v:,.{decimals}f}'
def pct(v,decimals=1): return 'N/A' if v is None else f'{v*100:.{decimals}f}%'
def money(v): return '$'+number(v,0)
def table(headers,rows,caption):
    return '<div class="table-wrap" tabindex="0" role="region" aria-label="'+e(caption)+'"><table><caption>'+e(caption)+'</caption><thead><tr>'+''.join('<th scope="col">'+e(str(h))+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+e(str(c))+'</td>' for c in row)+'</tr>' for row in rows)+'</tbody></table></div><p class="table-hint">On narrow screens, scroll the table to see every column.</p>'
def details(title,body): return f'<details><summary>{e(title)}</summary><div class="detail-body">{body}</div></details>'
def section(id,title,body): return f'<section id="{id}"><h2>{e(title)}</h2>{body}</section>'
def metrics(items): return '<div class="metrics">'+''.join(f'<div class="metric"><span>{e(k)}</span><strong>{e(str(v))}</strong></div>' for k,v in items)+'</div>'
def bars(rows,maximum=100):
    return '<div class="bars">'+''.join(f'<div><div class="bar-label"><span>{e(k)}</span><strong>{e(label)}</strong></div><div class="bar-track"><div class="bar-fill" style="width:{max(0,min(100,v/maximum*100)):.3f}%"></div></div></div>' for k,v,label in rows)+'</div>'
def linechart(series,title,unit='value'):
    n=max(len(x[1]) for x in series); vals=[v for _,vs in series for v in vs]; low=min(vals); high=max(vals); span=high-low or 1
    paths=[]
    for i,(name,vs) in enumerate(series):
        pts=' '.join(f'{70+j/max(1,len(vs)-1)*610:.1f},{240-(v-low)/span*200:.1f}' for j,v in enumerate(vs))
        paths.append(f'<polyline fill="none" stroke="{COLORS[i%len(COLORS)]}" stroke-width="2.5" points="{pts}"/>')
    return f'<figure><h3>{e(title)}</h3><div class="chart-range">Range: {number(low,0)} – {number(high,0)}</div><svg class="chart-svg" viewBox="0 0 720 275" role="img" aria-label="{e(title)}; underlying values available below"><line class="axis" x1="70" y1="240" x2="680" y2="240"/>{"".join(paths)}</svg><div class="legend">'+''.join(f'<span style="--series:{COLORS[i%len(COLORS)]}">{e(name)}</span>' for i,(name,_) in enumerate(series))+f'</div><figcaption>{e(unit)}. The horizontal axis runs from the first to the last observation in the stated period. Exact dated values are in the evidence download.</figcaption></figure>'
def review(c):
    r=c['review']; return '<div class="card review"><div class="eyebrow">Research-review conclusion</div><h2>'+e(r['status'])+'</h2>'+''.join('<p>'+e(x)+'</p>' for x in r['reasons'])+'<p class="muted">Economic bank/issuer exposure remains unassessable without dated ETF holdings. This is a review outcome, not investment approval.</p></div>'
def shell(c,page,title,subtitle,body):
    m=c['manifest']; base=m['case_url']; nav=''.join(f'<a href="{base}{"" if p=="overview" else p}"'+(' aria-current="page"' if p==page else '')+f'>{LABELS[p]}</a>' for p in ['overview','risk','scenarios','models','decision','performance','research'])
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="A reproducible Canadian bank market-stress research review."><title>{e(title)} | Northern Signal</title><link rel="stylesheet" href="{base}assets/review.css"></head><body data-snapshot="{m['snapshot_id']}"><a class="skip button" href="#main-content">Skip to main content</a><nav class="global" aria-label="Primary navigation"><div class="nav-inner"><a class="brand" href="{base}">Northern Signal</a><button id="nav-toggle" class="secondary" aria-expanded="false" aria-controls="nav-links">Menu</button><div class="nav-links" id="nav-links">{nav}</div></div></nav><main id="main-content"><div class="case-meta"><span class="badge {"good" if m["source_status"]=="downloaded_verified" else "warning"}">{ {"downloaded_verified":"Downloaded data verified","synthetic":"Synthetic demonstration"}.get(m["source_status"],"Origin unverified")}</span><span class="badge">Features through {m['feature_date']}</span><a class="badge" href="{base}research#reproduce">Pinned research case</a></div><div class="eyebrow">Canadian bank market-stress research</div><h1>{e(title)}</h1><p class="intro">{e(subtitle)}</p>{body}<div class="update-box"><strong>Keep this review reproducible</strong><p class="muted">This case stays pinned while you explore. Checking for updates does not download market data or train a model.</p><button id="check-update" class="secondary">Check for updated data</button><p class="status" id="update-status" role="status" aria-live="polite"></p><a id="open-update" class="button" hidden>Open updated case</a></div></main><footer><p>Research simulation. No real trades are placed. Market co-movement is not identified causal contagion; historical results do not establish future profitability.</p><div class="footer-links"><a href="{base}research#limitations">Evidence boundaries</a><a href="{base}review">Review brief</a><a href="{base}case.json" download>Download case evidence</a><a href="https://github.com/davidgold00/canadian-bank-contagion-rl/actions/workflows/refresh-research.yml">Owner rebuild workflow</a></div></footer><script type="module" src="{base}assets/update.js"></script></body></html>'''
def nextlink(c,page,label): return f'<div class="next"><p>Continue the research review</p><a class="button" href="{c["manifest"]["case_url"]}{page}">{e(label)} →</a></div>'
def overview(c):
    base=c['manifest']['case_url']; top=c['components'][:3]
    content='<div class="hero-grid"><div class="card"><h2>What is the market telling us?</h2><div class="metric-number">'+number(c['score'])+' <small>/ 100 stress index</small></div><p class="muted">A historical ranking of five market indicators, not a probability of bank failure.</p>'+bars([(r['component'],r['contribution'],number(r['contribution'])+' points') for r in top],20)+f'<a class="button" href="{base}risk">Walk through this review →</a></div>'+review(c)+'</div>'
    content+=section('journey','Four questions. One review.', '<div class="step-list">'+''.join(f'<a href="{base}{p}"><small>{i:02d} · {label}</small><strong>{question}</strong><p>{description}</p></a>' for i,p,label,question,description in [(1,'risk','Observe','Why is the score at this level?','Reconstruct the five inputs and inspect bank co-movement.'),(2,'decision','Inspect','What allocation is proposed?','Compare actual paper holdings with one consistent mandate.'),(3,'decision#review','Review','Does the evidence support it?','Separate model constraints, editorial guidance and unknown coverage.'),(4,'performance','Challenge','Did complexity earn its place?','Compare corrected simulations with simple alternatives.')])+'</div>')
    content+=section('dependencies','What actually feeds the decision?', '<div class="flow"><div class="flow-row"><span class="flow-node">Prices + lagged macro</span><span class="flow-arrow">→</span><span class="flow-node">Market-stress score</span></div><div class="flow-row"><span class="flow-node">Price/feature history + mandate + holdings</span><span class="flow-arrow">→</span><span class="flow-node">CVaR proposal</span><span class="flow-arrow">→</span><span class="flow-node">Evidence + guidance review</span></div></div><p class="muted">Scenarios, classifier evaluation and PPO comparisons are supporting experiments. They do not approve this allocation or silently change its weights.</p>')
    content+=f'<div class="actions"><a class="button secondary" href="{base}scenarios">Explore a hypothetical shock</a><a class="button secondary" href="{base}review">Open the review brief</a></div>'
    return shell(c,'overview','Does the evidence support this allocation?','Examine Canadian bank market stress, inspect a model proposal, and decide what the research can support.',content)

def risk(c):
    comp=c['components']; rows=[]
    for x in comp:
        raw=pct(x['raw']) if x['feature'] in ['avg_bank_vol_21d','XFN.TO_drawdown_63d'] else number(x['raw'],2)
        rows.append([x['component'],raw+' · '+x['unit'],x['window'],number(x['percentile'])+'th',pct(x['weight'],0),number(x['contribution'])])
    body=metrics([('Composite index',number(c['score'])+'/100'),('Percentile of historical index',number(c['score_percentile'],0)+'th'),('Available components',str(c['component_coverage']['current'])+'/5')])
    body+=section('composite-score','Reconstruct the score', '<p>Each available indicator is ranked against its own history through the observation date. Its percentile contributes equally to the composite. These are score contributions, not predictive feature importance.</p>'+bars([(r['component'],r['contribution'],number(r['contribution'])+' points') for r in comp],20)+table(['Component','Observed value','Window','Stress percentile','Weight','Points'],rows,'Current score construction'))
    slope=next((x['raw'] for x in comp if x['feature']=='slope_10y_2y'),None)
    body+=f'<div class="callout"><strong>The curve is {"not inverted" if slope is not None and slope>=0 else "inverted"}.</strong><p>The feature uses a 10Y-minus-2Y slope of {number(slope,2)} percentage points. Inversion ranks max(−slope, 0). Tied zero values can have a nonzero percentile, so a non-inverted curve can still contribute index points. This is a ranking convention, not evidence of inversion.</p></div>'
    body+=details('How to interpret the scale and missing inputs',f'<p>The index is not a crisis probability. The historical index percentile ranks the composite itself, a different quantity from the five input ranks. Equal weights and overlapping indicators are modeling choices.</p><p>{c["component_coverage"]["incomplete_history_rows"]} historical rows have fewer than five available components. Early ranks and filled scores must not be interpreted as equally complete evidence. Oil, CAD and node stress do not directly enter the five-component composite.</p>')
    body+=linechart([('Composite index',[r['score'] for r in c['history']])],'Recent market-stress index','0–100 index; '+c['history'][0]['date']+' to '+c['history'][-1]['date'])
    body+=details('Dated score observations',table(['Date','Index','Available components'],[[r['date'],number(r['score']),r['components']] for r in c['history']],'Last 252 observations'))
    corr=c['correlation']; banks=list(corr)
    body+=section('network','How independently are the banks moving?',f'<p>Average 63-session return correlation is <strong>{number(c["mean_correlation"],2)}</strong>. This describes co-movement and the observed diversification available within the sector. It does not identify causal transmission.</p>'+table(['Bank']+banks,[[b]+[number(corr[x][b],2) for x in banks] for b in banks],'63-session return correlations')+table(['Bank','Node stress'],[[b,number(c['node_stress'][b])+'/100'] for b in sorted(banks,key=lambda b:-c['node_stress'][b])],'Supporting bank-level stress'))
    body+=details('Transformations, historical sample counts and source dates',table(['Component','Adverse transformation','Transformed value','Historical observations','Feature as of'],[[x['component'],'max(−slope, 0)' if x['feature']=='slope_10y_2y' else 'absolute drawdown' if 'drawdown' in x['feature'] else 'unchanged raw indicator',number(x['transformed'],4),x['history_observations'],c['manifest']['feature_date']] for x in comp],'Feature dates use the stated market/macro availability convention'))
    body+=details('Three distinct graph definitions','<p>Risk: 63-session correlations and weighted connectivity at absolute correlation ≥0.35. Scenarios: 126-session positive correlations, zero self-links, row normalization. Optimizer: its 126-return window, weighted centrality and configured graph penalties. These are separate constructions, not one calibrated contagion model.</p>')
    return shell(c,'risk','Explain the observed market stress','Start with the index components, then examine how closely bank returns move together.',body+nextlink(c,'decision','Inspect the allocation proposal'))

def decision(c):
    p=c['proposal']; run=c['paper_run']; base=c['manifest']['case_url']; last=c['last_scheduled_target']
    body=section('review','What should the reviewer conclude?',review(c))
    body+=metrics([('Actual paper value',money(run['metrics']['ending_value'])),('Proposal cash',pct(p['weights'][-1])),('Editorial cash guidance',c['guidance']['cash_text'])])
    body+=f'<p>Actual holdings are marked through {c["manifest"]["feature_date"]}. The last scheduled target was decided on {last["decision_date"]} for execution on {last["execution_date"]}. The proposal below uses the same paper mandate and actual current holdings as its prior; it is an off-cycle research solve.</p>'
    body+=section('allocation','What changes in the indicative proposal?',table(['Asset','Actual holding','Proposal','Difference','Interpretation','1% trade threshold'],[[r['asset'],pct(r['current']),pct(r['target']),number(0 if abs(r['delta'])<.00005 else r['delta']*100,2)+' pp',r['action'],'Yes' if r['trade_threshold_met'] else 'No' if r['asset']!='cash' else 'Balance'] for r in c['allocation_rows']],'One portfolio and proposal identity across every component'))
    body+='<p class="muted">BUY/SELL describes an indicative difference, not an executed order. Display materiality is 0.10 percentage points; simulated execution ignores risky-asset trades below 1% of pre-trade NAV. Cash is a balance.</p>'
    body+=details('Cost-aware order preview and dated scheduled target',f'<p>At unchanged current marks, estimated transaction costs are {money(p["preview"]["cost"])} at 5 basis points per absolute risky-asset trade. Actual next-close prices will differ.</p>'+table(['Asset','Illustrative notional','Post-cost weight','Last scheduled target'],[[a,money(p['preview']['notionals'][a]),pct(p['preview']['post_cost_weights'][i]),pct(last['weights'][i])] for i,a in enumerate(run['assets'])],'Preview only; not an order submission'))
    body+=section('constraints','Separate model rules from review guidance',table(['Model constraint','Observed','Limit','Result'],[[r['Constraint'].replace('total financial exposure','modeled financial proxy'),pct(r['Value']),pct(r['Limit']) if isinstance(r['Limit'],(int,float)) else str(r['Limit']),r['Status']] for r in p['constraint_checks']],'Constraints belonging to this proposal')+f'<div class="callout warning"><p>Editorial cash guidance is {e(c["guidance"]["cash_text"])}. It is not imposed inside this optimizer. Economic bank and issuer exposure is not assessable from the existing proxy alone.</p></div>')
    assets=run['assets']; w=p['weights']; direct=sum(w[assets.index(a)] for a in assets[:6]); xfn=w[assets.index('XFN.TO')]; xiu=w[assets.index('XIU.TO')]
    body+=metrics([('Direct Big Six',pct(direct)),('XFN financial-sector ETF',pct(xfn)),('XIU broad-market ETF',pct(xiu))])
    body+=f'<p>The modeled financial proxy is <strong>{pct(direct+xfn)}</strong>: direct Big Six plus XFN. It excludes XIU look-through and is not full economic bank exposure. Direct single-name caps do not constrain issuer exposure through ETFs.</p>'
    pressure=.45*c['score']/100+.30*p['diagnostics']['graph_density']+.25*p['diagnostics']['average_correlation']; uplift=.4*pressure
    body+=section('worked-review','From observation to a review outcome',f'<ol><li>The {number(c["score"])} index enters the existing regime lookup. Current proposal limits are {pct(p["constraints"]["max_single_name_weight"])} per direct bank, {pct(p["constraints"]["max_bank_exposure"])} financial proxy, and at least {pct(p["constraints"]["min_cash_weight"])} cash.</li><li>The configured graph pressure adds a common {pct(uplift,2)} covariance-entry uplift to the direct-bank block, before additional node factors and PSD projection. It is not a {pct(uplift,2)} volatility increase.</li><li>The joint objective selects {pct(xfn)} XFN, {pct(xiu)} XIU and {pct(w[-1])} cash, using actual holdings as its prior. Current proxy-cap slack is {number((p["constraints"]["max_bank_exposure"]-direct-xfn)*100,2)} percentage points. A binding constraint does not identify its isolated causal contribution.</li><li>Editorial cash guidance and missing ETF look-through determine the review reasons above. Solver status: {e(p["diagnostics"]["status"])}.</li></ol>')
    body+=section('mechanism','Why is this a model proposal, not a mandate?', '<p>The optimizer balances a clipped trailing-return estimate against historical tail loss, covariance, graph terms and turnover, subject to the selected paper constraints. The score informs regime limits and graph treatment. None of those inputs, alone, explains an exact final weight.</p><p>ETFs retain historical market-return risk but are outside the six-bank graph’s explicit node treatment. Controlled comparisons in Models test how much that modeling choice changes this proposal.</p>')
    body+=details('Proposal identity and configuration',f'<p>Proposal: <code>{p["id"]}</code>. As of {p["as_of"]}. Scope: {p["kind"]}.</p><pre>{e(json.dumps(p["configuration"],indent=2))}</pre><p>The former snapshot configuration remains a separate experiment. Its equal-weight prior and different penalties are not this paper portfolio’s next rebalance.</p>')
    body+=f'<div class="actions"><a class="button secondary" href="{base}review">Open printable review brief</a><a class="button secondary" href="{base}models#cvar-strategy">Inspect controlled diagnostics</a></div>'
    return shell(c,'decision','Review one coherent allocation proposal','The conclusion separates model constraints, editorial guidance, and evidence the system does not have.',body+nextlink(c,'performance','Challenge the historical evidence'))

def performance(c):
    runs=c['benchmarks']; common=runs['CVaR paper mandate']; rows=[]
    for name,r in runs.items():
        m=r['metrics'];rows.append([name,money(m['ending_value']),pct(m['cumulative_return']),pct(m['max_drawdown']),number(m['sharpe'],2),money(m['costs'])])
    body=f'<div class="callout"><p><strong>Corrected next-close simulations:</strong> {common["start"]} to {common["end"]}, {common["metrics"]["observations"]} observations, $100,000 original capital. Information at close t can trade only at close t+1. This period does not include the 2020 pandemic crash.</p></div>'
    body+=section('strategy-performance','What did the added complexity deliver?',table(['Strategy / reference','Ending wealth','Return on original capital','Max drawdown','Sharpe (zero risk-free)','Costs'],rows,'Same-period, costed research comparisons'))
    if 'PPO corrected comparator' in runs:
        a=common['metrics'];b=runs['PPO corrected comparator']['metrics']; gap=a['ending_value']-b['ending_value'];dd=abs(b['max_drawdown'])-abs(a['max_drawdown'])
        body+=f'<div class="callout warning"><p>CVaR minus PPO ending wealth: <strong>{money(gap)}</strong> ({pct(gap/b["ending_value"])} relative to PPO). CVaR’s drawdown magnitude is {number(abs(dd)*100,2)} percentage points {"smaller" if dd>=0 else "larger"} ({pct(abs(dd)/abs(b["max_drawdown"]))} relative change); cumulative return differs by {number((a["cumulative_return"]-b["cumulative_return"])*100,2)} points. These are observed trade-offs, not a universal ranking.</p></div>'
        simple=[runs[n]['metrics'] for n in ['Equal-weight feasible','Development-fixed allocation']]
        dominates=all(b['ending_value']>x['ending_value'] and abs(b['max_drawdown'])<=abs(x['max_drawdown']) for x in simple)
        body+='<p><strong>'+('PPO improves these observed wealth/drawdown comparisons; robustness beyond this period is unestablished.' if dominates else 'Incremental value not demonstrated across both ending wealth and drawdown against the simple comparators in this evaluation.')+'</strong> A different mandate could value the trade-offs differently.</p>'
    series=[(name,[x['portfolio_value'] for x in r['ledger']]) for name,r in runs.items() if name in ['CVaR paper mandate','PPO corrected comparator','Equal-weight feasible','Development-fixed allocation']]
    body+=linechart(series,'Growth of original capital','CAD; '+common['start']+' to '+common['end'])
    if 'PPO corrected comparator' in runs:
        equal=runs['Equal-weight feasible']['metrics'];ppo=runs['PPO corrected comparator']['metrics'];wealth=equal['ending_value']-ppo['ending_value'];draw=abs(ppo['max_drawdown'])-abs(equal['max_drawdown'])
        body+=f'<p>The equal-weight feasible reference ends {money(abs(wealth))} {"higher" if wealth>=0 else "lower"} than PPO, with a {number(abs(draw)*100,2)}-percentage-point {"smaller" if draw>=0 else "larger"} drawdown magnitude. This simple reference is an essential part of the result.</p>'
    body+=details('Benchmark construction and comparability',f'<p>All new runs use 5 basis points per absolute risky-asset trade, a 1% per-asset trade threshold, next-close execution and zero cash interest. CVaR assesses a target every ten observations. PPO and the fixed target references assess daily.</p><p>Equal-weight feasible uses the existing PPO caps. Development-fixed allocation was solved on {c["static_fixed_on"]}, before the final period, then frozen. XFN/XIU buy-and-hold are costed exposure references with different constraints. The fixed reference weights use no final-test outcomes. Targets are constrained; drift, costs and the per-asset trade threshold can leave realized holdings temporarily beyond a target cap. The variability table reports those realized ranges instead of claiming continuous cap compliance.</p>'+table(['Asset','Development-fixed target'],[[a,pct(w)] for a,w in zip(common['assets'],c['static_weights'])],'Weights fixed before final evaluation'))
    body+=section('paper-portfolio','Actual holdings at the end of the paper path',table(['Asset','Actual weight','Last scheduled target'],[[a,pct(w),pct(c['last_scheduled_target']['weights'][i])] for i,(a,w) in enumerate(zip(common['assets'],c['actual_weights']))],'Holdings can drift between scheduled decisions'))
    variable=[]
    for name,r in runs.items():
        if name not in ['CVaR paper mandate','PPO corrected comparator','Equal-weight feasible','Development-fixed allocation']: continue
        for measure,d in r['variability'].items():
            if measure=='individual_std_pp': continue
            variable.append([name,measure.replace('_',' '),pct(d['mean']),pct(d['min']),pct(d['max']),number(d['std_pp'],3)+' pp',pct(r['metrics']['average_turnover'],2)])
    body+=section('risk-activity','Did the allocations actually change?',table(['Run','Measure','Mean','Minimum','Maximum','Level std. dev.','Mean daily turnover'],variable,'Exposure variability includes original cash-only starting state'))
    after=[]
    for name,r in runs.items():
        if name not in ['PPO corrected comparator','Equal-weight feasible']:continue
        import statistics
        values=[sum(w[:7]) for w in r['weights'][1:]]
        after.append([name,pct(statistics.mean(values)),number(statistics.pstdev(values)*100,3)+' pp',pct(max(values)),len(values)])
    body+=details('Exclude the initial cash-only observation',table(['Run','Mean financial proxy','Level std. dev.','Maximum realized proxy','Post-initial observations'],after,'Same saved holdings; a separate diagnostic removes the initial all-cash state'))
    body+=details('Individual allocation variability',table(['Run','Asset','Weight-level standard deviation'],[[name,a,number(v,3)+' pp'] for name,r in runs.items() for a,v in r['variability']['individual_std_pp'].items() if name in ['CVaR paper mandate','PPO corrected comparator','Equal-weight feasible','Development-fixed allocation']],'Variability includes the original cash-only state'))
    body+=details('Dated portfolio values',table(['Date']+list(runs),[[row['date']]+[money(r['ledger'][i]['portfolio_value']) for r in runs.values()] for i,row in enumerate(common['ledger'])],'Every common-period observation, CAD'))
    body+=details('Recent CVaR simulated transactions',table(['Execution close','Decision close','Asset','Signed notional','Cost','Pre-trade weight','Target'],[[t['date'],t['decision_date'],t['asset'],money(t['notional']),money(t['cost']),pct(t['pre_weight']),pct(t['target_weight'])] for t in reversed(common['trades'][-25:])],'Observed trades; not causal explanations'))
    body+=details('Metric definitions and exact dated returns',f'<p>Cumulative return and CAGR use original capital, including initial costs. Volatility is population daily standard deviation × √252. Sharpe uses a zero risk-free rate. Undefined ratios are N/A. Daily historical CVaR is the negative mean of returns at or below their fifth percentile.</p><p>The legacy Sortino variant divides mean return by the standard deviation of negative returns only; it is not standard root-mean-square downside deviation. Days below original capital is not time below a previous peak.</p><p><a href="{c["manifest"]["case_url"]}case.json" download>Download every dated NAV, daily return, target, trade and metric</a>.</p>'+table(['Run','CAGR','Daily CVaR 95%','Legacy Sortino variant','Days below original capital'],[[n,pct(r['metrics']['cagr']),pct(r['metrics']['daily_cvar_95']),number(r['metrics']['legacy_sortino_variant'],2),r['metrics']['days_below_original_capital']] for n,r in runs.items()],'Definitions apply to these new method-version runs'))
    body+=section('legacy','Keep the former results in their original context','<p>The published September 4 legacy comparison used a July 2022 common start, different timing and an unverified PPO training boundary. Its extended PPO period began in January 2020 and reported −35.0% maximum drawdown. These are not interchangeable experiments.</p>'+f'<a href="{c["manifest"]["case_url"]}legacy-evidence.json" download>Download preserved legacy run evidence</a>')
    return shell(c,'performance','Challenge the historical evidence','Compare complexity with simple allocations under explicit execution and cost assumptions.',body+nextlink(c,'review','Read the final review brief'))

def models_page(c):
    p=c['proposal'];base=c['manifest']['case_url'];body=section('cvar-strategy','CVaR: an allocation proposal under a stated mandate', '<p>Inputs are return history, covariance, graph metrics, the market-stress score and actual prior holdings. Output is a constrained allocation. Its role is to propose a research portfolio; the review process can still hold that proposal.</p>'+metrics([('Clipped trailing return estimate',pct(p['expected_return'])),('Historical daily CVaR 95%',pct(p['daily_cvar_95'])),('Tail observations',str(p['tail_count'])+' / '+str(p['sample_count']))])+f'<p>The return input blends 35% of the 63-observation mean and 65% of the 126-observation mean, annualizes them, and clips individual estimates to −25% to +35%. It is not a forecast of a {pct(p["expected_return"])} gain. Current-target CVaR applies fixed weights to the last 126 returns; Performance evaluates the rebalanced strategy over its full period.</p>')
    body+=table(['Graph diagnostic','XFN','XIU','Cash','Daily CVaR'],[[r['name'],pct(r['weights'][6]),pct(r['weights'][7]),pct(r['weights'][8]),pct(r['daily_cvar_95'])] for r in c['diagnostics']],'Same inputs, mandate and prior holdings; only the identified graph mechanism changes')
    body+='<p class="muted">These controlled model comparisons test sensitivity to explicit graph treatment. They do not identify economic causality or establish an additive allocation explanation. ETF ordinary return/covariance risk remains present.</p>'
    body+=section('sensitivity','Risk-preference sensitivity',table(['Risk aversion','Annual return estimate','Annual volatility estimate','Daily CVaR','Cash'],[[r['risk_aversion'],pct(r['expected_return']),pct(r['volatility']),pct(r['daily_cvar_95']),pct(r['weights'][-1])] for r in c['sensitivities']],'Independent solves with the same prior; the selected proposal uses risk aversion 6'))
    body+=details('Alternative configuration and covariance interpretation',f'<p>The former snapshot is retained separately: risk aversion 7, CVaR penalty 9, node penalty 0.9, turnover penalty 0.15, equal-weight prior, 20% direct-bank cap, 70% proxy cap and 5–60% cash.</p><p>Its current cash is {pct(c["alternative"]["weights"][-1])}; it does not replace the primary paper-mandate proposal.</p><p>Graph pressure = 0.45 × score/100 + 0.30 × density + 0.25 × average absolute correlation. At strength 0.40 this multiplies direct-bank covariance entries by 1 + 0.40 × pressure, with additional per-bank factors and a positive-semidefinite projection. A covariance uplift is not the same percentage increase in volatility.</p>')
    body+=section('rl-strategy','PPO: an experimental comparator', '<p>The corrected policy observes 21 sessions of asset returns, forty explicitly named market features and current holdings. It uses the same next-close ledger as evaluation. Architectural nonlinearity does not prove useful adaptation.</p>')
    if c['ppo']:
        m=c['ppo'];body+=table(['Seed','Completed steps','Validation reward','Final-test ending wealth','Final-test drawdown','Selection'],[[r['seed'],r['completed_steps'],number(r['validation_reward'],6),money(r['test_metrics']['ending_value']),pct(r['test_metrics']['max_drawdown']),'Validation-selected' if r['seed']==m['selected_seed'] else 'Reported comparator'] for r in m['candidates']],'All seeds; checkpoint selected before final-test outcomes were inspected')
        body+=f'<p>The request was 100,000 steps per seed; PPO completed rollout blocks of {m["candidates"][0]["completed_steps"]:,} steps. Network architecture and reward coefficients were preserved.</p>'
        body+=details('Exact observations and training provenance',f'<p>The composite score is {"included" if m["risk_inputs"]["composite_score"] else "not explicitly included"} among these forty features. Returns can convey market stress indirectly. There is no claim that the policy explicitly reads graph centrality.</p><pre>{e(json.dumps(m["schema"],indent=2))}</pre><p>Model identity: <code>{m["id"]}</code>. Feature order and asset order are validated, not inferred from matching dimensions.</p>')
    else:body+='<div class="callout warning"><p>No compatible corrected PPO evaluation is attached to this case. The legacy policy is not substituted.</p></div>'
    body+=details('What the reward terms actually encourage','<p>Return, drawdown and turnover depend on the portfolio path. The volatility input is cross-sectional dispersion of asset returns. Contagion and stress use the same market score and are identical across actions at a given state. Moving to cash does not directly reduce those market-level terms.</p>'+table(['Term','Coefficient','Allocation-dependent at a fixed market state?'],[['Portfolio return',1,'Yes'],['Asset-return dispersion',-.20,'No'],['Absolute drawdown',-.30,'Path-dependent'],['Risky-asset turnover',-.02,'Yes'],['Market contagion score / 100',-.15,'No'],['Same market score / 100',-.10,'No'],['Excess return versus XFN',.25,'Yes']],'Reward design retained; no silent holdings-weighted penalty introduced'))
    if c.get('reward_diagnostic'):
        reward=c['reward_diagnostic']
        body+=details('Worked reward decomposition for alternative queued allocations',f'<p>Fixed observed market state on {reward["date"]}; same prior holdings and peak. Under next-close timing, target changes affect this step through execution costs/turnover; new holdings cannot earn its already-observed market move.</p>'+table(['Queued target','Return','Dispersion','Drawdown','Turnover','Contagion','Stress','Excess','Total'],[[r['action']]+[number(r['terms'][k],6) for k in ['return','dispersion','drawdown','turnover','contagion','stress','excess']]+[number(r['total'],6)] for r in reward['rows']],'Each cell is its weighted reward contribution; identical market terms are visible'))
    hcash=max(.05,min(.75,(c['score']-35)/65)); hxfn=max(0,min(.25,(60-c['score'])/100))
    body+=details('Standalone heuristic: a separate reference',f'<p>The legacy deterministic heuristic does not invoke PPO. Cash = clip((score−35)/65, 5%, 75%) = {pct(hcash)}. XFN = clip((60−score)/100, 0%, 25%) = {pct(hxfn)}. Remaining bank weight follows inverse node stress; XIU is excluded. It is not the selected portfolio and is not evidence of trained behavior.</p>')
    body+=section('validation','Can a classifier improve on simply carrying the score forward?','<p>The target is the composite score five dataset observations ahead at or above a training-only 80th-percentile threshold. It does not predict bank failure, portfolio approval or profitable timing.</p>')
    classifier=c['classifier']
    if classifier:
        body+=table(['Model / baseline','AUROC','Average precision','Precision','Recall','Positive prevalence'],[[n,number(m['auroc'],3),number(m['average_precision'],3),pct(m['precision']),pct(m['recall']),pct(m['prevalence'])] for n,m in classifier['test'].items()],'Final-test results on identical eligible observations')
        rf=classifier['test'][classifier['selected_model']];pers=classifier['test']['Current-score persistence'];word='does not beat' if rf['average_precision']<=pers['average_precision'] else 'beats'
        body+=f'<div class="callout"><p>The validation-selected {e(classifier["selected_model"].lower())} {word} current-score persistence on final-test average precision. A high AUC alone does not establish incremental value.</p></div>'
        body+=details('Evaluation dates, label coverage and confusion counts',table(['Partition','Feature start','Feature end','Last label outcome','Rows'],[[n,r['start'],r['end'],r['last_outcome'],r['count']] for n,r in classifier['partitions'].items()],'Chronological partitions with crossing labels purged')+f'<p>Training-only threshold: {number(classifier["threshold"],3)}. {classifier["excluded_unavailable_or_incomplete"]} rows excluded for incomplete features or unavailable future outcomes; {classifier["purged_boundary_rows"]} more removed at partition boundaries. Decision threshold stays 0.50. No preprocessing fits final-test data.</p>'+table(['Model','TN','FP','FN','TP'],[[n]+m['confusion_matrix_tn_fp_fn_tp'] for n,m in classifier['test'].items()],'Actual final-test confusion counts')+table(['Development validation period','Model','AUROC','Average precision'],[[f['validation_start']+' → '+f['validation_end'],n,number(m['auroc'],3),number(m['average_precision'],3)] for f in classifier['development_folds'] for n,m in f['metrics'].items()],'Expanding development folds, outside the final test'))
    body+='<p class="muted">Legacy approximately 0.97 AUC used full-sample label calibration, cross-boundary labels and incorrectly negative terminal labels. It is archived, not a headline validation result.</p>'
    return shell(c,'models','Ask each model a specific question','Allocation, prediction and scenario sensitivity have different inputs, outputs and evidence standards.',body+nextlink(c,'decision','Return to the proposal review'))

def scenarios_page(c):
    data=c['scenarios'];path=data['default_path']; initial=path[0];final=path[-1];base=c['manifest']['case_url']
    controls='<div class="controls"><label class="control">Scenario preset<select id="scenario-preset">'+''.join(f'<option{ " selected" if n==data["default"] else ""}>{e(n)}</option>' for n in data['presets'])+'</select></label><label class="control">Severity: <output id="severity-label">100%</output><input id="severity" type="range" min="50" max="150" step="10" value="100"></label><button id="scenario-reset" class="secondary">Reset scenario</button><button id="copy-scenario" class="secondary">Copy scenario link</button></div><p id="scenario-status" class="status" role="status" aria-live="polite">Liquidity squeeze at 100% severity.</p>'
    body=controls+'<div class="callout"><p>Presets are assumed starting intensities. Five abstract propagation steps have no calibrated calendar duration. The results are not portfolio losses, probabilities or optimizer inputs.</p></div>'
    body+=f'<div class="metrics"><div class="metric"><span>Initial mean intensity</span><strong id="initial-mean">{number(sum(initial)/6)}</strong></div><div class="metric"><span>Final mean intensity</span><strong id="final-mean">{number(sum(final)/6)}</strong></div><div class="metric"><span>Banks at cap</span><strong id="cap-count">0 / 6</strong></div></div>'
    body+=section('transmission','What changed from the assumption to the output?', '<div class="table-wrap" tabindex="0" role="region" aria-label="Scenario results"><table><caption id="scenario-caption">Liquidity squeeze · 100% severity</caption><thead><tr><th>Bank</th><th>Initial intensity</th><th>Final intensity</th><th>Initial rank → final rank</th><th>Uniform-network final</th><th>Observed → uniform rank</th><th>No-spillover final</th></tr></thead><tbody id="scenario-rows"></tbody></table></div><p id="scenario-totals"></p><p id="leader-note"></p><p id="step-example"></p>')
    body+=section('assumptions','The increase in total intensity is partly configured', '<p id="aggregate-explanation">With all outgoing rows normalized and no clipping, total intensity increases by 15% each step: 1.15⁵ ≈ 2.011. The liquidity preset’s initial mean of 37 therefore becomes approximately 74.42. The network redistributes intensity; this aggregate increase is not a discovered economic effect.</p><p>The uniform-network diagnostic holds the initial shocks and recurrence fixed. The no-spillover diagnostic removes the spillover term, so its aggregate amplification differs. Neither establishes causal contagion.</p>')
    body+=details('Exact recurrence, paths and preset values','<p>A has positive 126-session correlations, zero diagonal and rows normalized by outgoing sum. Zero rows remain zero. s₀ = clip(severity × preset, 0, 100); sₖ₊₁ = clip(0.70sₖ + 0.45Aᵀsₖ, 0, 100), for five steps. Clipping and zero rows invalidate the simple 1.15 aggregate identity. Saturation removes differentiation.</p><div id="scenario-paths"></div>'+table(['Bank']+list(data['presets']),[[b]+[v[i] for v in data['presets'].values()] for i,b in enumerate(data['banks'])],'Preset magnitudes are assumptions'))
    body+=f'<p><a id="scenario-review" class="button secondary" href="{base}review">Include this sensitivity in the review brief</a></p><noscript><p>Interactive scenarios require JavaScript. Default liquidity results:</p>'+table(['Bank','Initial','Final'],[[b,number(initial[i]),number(final[i])] for i,b in enumerate(data['banks'])],'Default liquidity at 100%')+'</noscript>'
    body+='<script id="scenario-data" type="application/json">'+json.dumps(data).replace('<','\\u003c')+'</script>'+f'<script type="module" src="{base}assets/scenario.js"></script>'
    return shell(c,'scenarios','Explore assumptions and sensitivity','Change the initial shock and inspect how the configured network redistributes it.',body)

def research(c):
    m=c['manifest'];p=c['provenance'];base=m['case_url'];rows=[]
    for key in ['market','macro']:
        source=p[key]
        for series,date in source['quality']['last_observation'].items(): rows.append([source['provider'],series,date,source['retrieved_at']])
    body=section('data','What data supports this case?', '<p>These inputs were freshly downloaded with fallback disabled and recorded hashes. The earlier cache remains origin-unverified. A successful new download does not retroactively certify it.</p>'+table(['Provider','Series','Last observed date','Retrieved UTC'],rows,'Observation dates differ from retrieval, feature and publication dates')+f'<p>Feature date: {m["feature_date"]}. Build time: {m["generated_at"]}. Tradable prices are not forward-filled; incomplete sessions are excluded. Macro observations are forward-aligned with an explicit one-market-session delay. Actual historical release timestamps remain unavailable.</p>')
    body+=details('Completeness, staleness and source adjustments',f'<p>{len(p["quality"]["incomplete_dates"])} market dates lacked a required tradable or VIX observation and were excluded. Current macro age is {p["macro_age_days_latest"]} calendar days. This is a data-quality convention, not certification of historical release availability.</p><p>Yahoo Finance Close is requested with auto_adjust=True. Vendor split/dividend adjustments are used; dividends are not separately credited. Portfolio prices are treated as CAD. USD oil, VIX and CAD/USD are contextual features, not USD portfolio holdings. Housing, CDS and ETF holdings templates are unused.</p><pre>{e(json.dumps(p["quality"]["missing_counts"],indent=2))}</pre>')
    body+=section('methodology','Which calculation answers which question?',table(['Mechanism','Question','Feeds the current proposal?'],[['Composite market-stress score','How elevated are five historical market indicators?','Yes: regime rules and graph adjustment'],['Return-correlation graph','How closely do bank returns move?','Optimizer uses its own configured graph'],['CVaR optimizer','What allocation balances its objective under this mandate?','It generates the proposal'],['Scenario recurrence','What follows from an assumed shock and network?','No'],['Supervised classifier','Can future score rankings improve on persistence?','No'],['PPO historical comparator','Does a trained policy add evidence over simple allocations?','No'],['Bank attractiveness / standalone heuristic','What does an independent scoring rule suggest?','No']],'Actual computational dependencies'))
    body+=section('limitations','What the evidence cannot establish?', '<ul><li>Observed return correlations do not identify funding, counterparty or balance-sheet contagion.</li><li>ETF look-through is unavailable. Economic bank/issuer exposure remains unassessable.</li><li>Editorial guidance is not an optimized or empirically validated investment mandate.</li><li>Historical adjusted data lacks a complete vintage/release-time archive.</li><li>Zero cash interest, simplified 5-basis-point costs and next-close execution omit taxes, market impact and liquidity/slippage.</li><li>PPO retains allocation-independent market-risk reward terms; its architecture does not establish tactical value.</li><li>The classifier predicts the site’s own score, not bank failure or profitable timing.</li><li>Final-test coverage is one historical period, not evidence of future robustness.</li></ul>')
    body+=section('reproduce','Reproduce the same review', f'<p>Snapshot <code>{m["snapshot_id"]}</code> freezes the evidence used by all seven pages. Downloads include exact weights, dates, model identities, labels and NAV histories.</p><div class="actions"><a class="button secondary" href="{base}case.json" download>Case evidence JSON</a><a class="button secondary" href="{base}review.md" download>Review brief Markdown</a><a class="button secondary" href="{base}legacy-evidence.json" download>Legacy evidence</a></div>'+details('Source and artifact identities',f'<pre>{e(json.dumps(m,indent=2))}</pre><p>The source revision identifies the base commit; the source-tree hash additionally identifies the reviewed working implementation. Trained artifact and input hashes are preserved in the case evidence.</p>'))
    body+=section('references','Methods and owner operation', '<p>Market series: Yahoo Finance via yfinance. Macro series: Bank of Canada Valet. Production ingestion never substitutes synthetic data. A public update check reads the published manifest; only the owner workflow can rebuild and publish.</p><div class="footer-links">'+''.join(f'<a href="{base}{name}" download>{label}</a>' for name,label in [('methodology.md','Current methodology'),('model-card.md','Current model card'),('interview-prep.md','Interview walkthrough'),('implementation-log.md','Changes and verification')])+'</div>')
    return shell(c,'research','Trace the evidence behind the review','Separate data origin, information availability, model identity and interpretation.',body)

def brief_markdown(c):
    m=c['manifest'];top='; '.join(f'{x["component"]}: {x["contribution"]:.1f} points' for x in c['components'][:3])
    r=c['benchmarks']['CVaR paper mandate'];p=c['proposal']
    return f'''# Northern Signal — research review\n\nCase: {m['snapshot_id']}\nFeatures through: {m['feature_date']}\nSource status: {m['source_status']}; historical release timestamps incomplete.\n\n## Question\nDoes the evidence support this indicative allocation under the existing paper mandate?\n\n## Observation\nComposite market-stress score: {c['score']:.1f}/100, not a crisis probability.\nLargest contributions: {top}.\n\n## Proposal and holdings\nProposal: {p['id']}; actual prior holdings and existing CVaR paper configuration.\nActual paper cash: {c['actual_weights'][-1]:.1%}; proposal cash: {p['weights'][-1]:.1%}.\nEditorial cash guidance: {c['guidance']['cash_text']}.\n\n## Review disposition\n{c['review']['status']}\n{chr(10).join('- '+x for x in c['review']['reasons'])}\nEconomic bank/issuer exposure: not assessable without dated ETF look-through.\nThis is not investment approval.\n\n## Historical evidence\nCorrected next-close comparison: {r['start']} to {r['end']}.\nCVaR ending wealth: {money(r['metrics']['ending_value'])}; maximum drawdown: {pct(r['metrics']['max_drawdown'])}.\nCompare PPO and development-fixed / equal-weight allocations on the Performance page.\nThe classifier predicts future composite-score rankings, not profitable timing.\n\n## What could change the review?\n{chr(10).join('- '+x for x in c['review']['next_evidence'])}\n\n## Supporting sensitivities\nScenarios do not condition the optimizer. A selected scenario can be attached to the on-screen brief with its exact URL parameters.\n\n## Reproduction\nPinned case: {m['case_url']}\nExact weights, labels, histories and hashes: case.json\n'''

def brief(c):
    body=f'<div class="actions no-print"><button id="print-brief">Print / save PDF</button><a class="button secondary" href="{c["manifest"]["case_url"]}review.md" download>Download brief</a></div>'+review(c)
    body+=section('brief-observation','Observation and proposal',f'<p>The score is {number(c["score"])} / 100. '+e('; '.join(f'{x["component"]} contributes {x["contribution"]:.1f} points' for x in c['components'][:3]))+'.</p>'+table(['Asset','Actual','Indicative proposal'],[[a,pct(c['actual_weights'][i]),pct(c['proposal']['weights'][i])] for i,a in enumerate(c['benchmarks']['CVaR paper mandate']['assets'])],'One proposal, existing paper mandate'))
    body+=section('brief-evidence','Historical comparison',table(['Run','Ending wealth','Max drawdown'],[[n,money(r['metrics']['ending_value']),pct(r['metrics']['max_drawdown'])] for n,r in c['benchmarks'].items()],'Corrected same-period next-close simulations'))
    body+=section('brief-next','What would change this conclusion?','<ul>'+''.join('<li>'+e(x)+'</li>' for x in c['review']['next_evidence'])+'</ul><p>Historical macro release timestamps and economic ETF exposure remain incomplete. Scenarios and classifier results are separate supporting experiments.</p><div id="attached-scenario" class="callout" hidden></div>')
    body+='<script id="scenario-data" type="application/json">'+json.dumps(c['scenarios']).replace('<','\\u003c')+'</script>'+f'<script type="module" src="{c["manifest"]["case_url"]}assets/scenario.js"></script>'
    return shell(c,'decision','Research review brief','A reproducible conclusion, its evidence, and the information still needed.',body)

def render_case(case_path,output='build/current'):
    c=json.loads(Path(case_path).read_text());output=Path(output);sid=c['manifest']['snapshot_id']
    from src.research.publication import release_transaction
    with release_transaction(output,sid) as staging:
        if (output/'snapshots').exists(): shutil.copytree(output/'snapshots',staging/'snapshots')
        dest=staging/'snapshots'/sid
        # Existing identities are never overwritten. A changed renderer has a new source hash/case ID.
        previous=dest if dest.exists() else None
        fresh=staging/'new-case';fresh.mkdir()
        renderers={'overview':overview,'risk':risk,'decision':decision,'performance':performance,'scenarios':scenarios_page,'models':models_page,'research':research,'review':brief}
        for name,fn in renderers.items():
            html=fn(c);filename='index.html' if name=='overview' else name+'.html'
            (fresh/filename).write_text(html);(staging/filename).write_text(html)
        shutil.copytree(Path(__file__).with_name('assets'),fresh/'assets')
        shutil.copyfile(case_path,fresh/'case.json');write_json(fresh/'legacy-evidence.json',c['legacy'])
        (fresh/'review.md').write_text(brief_markdown(c))
        for source,target in [('reports/methodology.md','methodology.md'),('reports/model_card.md','model-card.md'),('docs/interview-prep.md','interview-prep.md'),('docs/implementation-log.md','implementation-log.md')]:
            shutil.copyfile(source,fresh/target)
        if previous:
            if tree_hashes(previous)!=tree_hashes(fresh): raise ValueError('Refusing to rewrite a pinned case')
            shutil.rmtree(fresh)
        else:
            dest.parent.mkdir(parents=True,exist_ok=True);fresh.rename(dest)
        write_json(staging/'publication-catalog.json',{'schema_version':1,'snapshot_id':sid,'files':{str(p.relative_to(staging)):digest(p) for p in sorted((staging/'snapshots').rglob('*')) if p.is_file()}})
        write_json(staging/'snapshot-manifest.json',c['manifest'])
        validate_site(staging)
    print('Rendered complete case:',output,sid,flush=True)
    return output

def tree_hashes(path):
    return {str(p.relative_to(path)):digest(p) for p in Path(path).rglob('*') if p.is_file()}

def validate_site(root):
    from html.parser import HTMLParser
    from urllib.parse import urlsplit,unquote
    class Links(HTMLParser):
        def __init__(self): super().__init__();self.links=[]
        def handle_starttag(self,tag,attrs):
            for k,v in attrs:
                if k in ['href','src'] and v:self.links.append(v)
    root=Path(root)
    for html in root.rglob('*.html'):
        parser=Links();parser.feed(html.read_text())
        for link in parser.links:
            url=urlsplit(link)
            if url.scheme or url.netloc or not url.path: continue
            target=root/unquote(url.path).lstrip('/') if url.path.startswith('/') else html.parent/unquote(url.path)
            if not any(p.is_file() for p in [target,target.with_suffix('.html'),target/'index.html']):raise ValueError(f'Broken local link: {html} → {link}')
    return True
